import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Georgeblad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bienvenid@!</h1>

        <div className={styles.services}>
          <h2>Servicios</h2>
          <div className={styles.serviceContainer} id="serviceContainer1">
            <Image
              src="/favicon.ico"
              alt="Picture of the author"
              width={80}
              height={80}
            />
            <h3>Servicio 1</h3>
            <p>
              Con este servicio ofrecemos información de la mejor calidad
              disponible en el mercado.
            </p>
          </div>
          <div className={`${styles.serviceContainer} ${styles.rojo}`}>
            <Image
              src="/favicon.ico"
              alt="Picture of the author"
              width={80}
              height={80}
            />
            <h3>Servicio 2</h3>
            <p>
              Con este servicio ofrecemos información de la mejor calidad
              disponible en el mercado.
            </p>
          </div>
          <div className={`${styles.serviceContainer} ${styles.amarillo}`}>
            <Image
              src="/favicon.ico"
              alt="Picture of the author"
              width={80}
              height={80}
            />
            <h3>Servicio 3</h3>
            <p>
              Con este servicio ofrecemos información de la mejor calidad
              disponible en el mercado.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <h4>Powered by Georgeblad.com</h4>
      </footer>
    </div>
  );
}
